stages:
  - build
  - deploy

build-flatpak:
  image: registry.gitlab.com/b0/flatpak-kde-docker
  stage: build
  before_script:
    - git submodule update --init --recursive
  script:
    - cd flatpak
    - flatpak-builder --force-clean --repo=repo build-dir org.eu.encom.spectral.yaml
    - flatpak build-bundle repo spectral.flatpak org.eu.encom.spectral
    - cd ../
  artifacts:
    paths:
    - flatpak/spectral.flatpak

build-appimage:
  image: registry.gitlab.com/b0/qt-docker
  stage: build
  before_script:
    - git submodule update --init --recursive
  script:
    - qmake CONFIG+=debug CONFIG+=qml_debug PREFIX=/usr
    - make
    - make INSTALL_ROOT=appdir install
    - /usr/bin/linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/org.eu.encom.spectral.desktop -appimage -qmldir=qml -qmldir=imports -unsupported-bundle-everything -unsupported-allow-new-glibc
  artifacts:
    paths:
    - Spectral*.AppImage
