stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-appimage:
  image: a12e/docker-qt:5.12-gcc_64
  stage: build
  before_script:
    - sudo apt-get update
    - sudo apt-get -y install apt-transport-https ca-certificates gnupg software-properties-common wget
    - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
    - sudo apt-add-repository -y 'deb https://apt.kitware.com/ubuntu/ xenial main'
    - sudo apt-get update
    - sudo apt-get -y install cmake
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get -y install gcc-9
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
    - sudo update-alternatives --config gcc
  script:
    - git clone https://gitlab.matrix.org/matrix-org/olm.git && cd olm
    - cmake . -Bbuild -LA -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=install -DBUILD_SHARED_LIBS=NO
    - cmake --build build --target install
    - cd ..
    - git clone https://github.com/frankosterfeld/qtkeychain.git && cd qtkeychain
    - cmake . -Bbuild -LA -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=install -DQTKEYCHAIN_STATIC=ON -DBUILD_TRANSLATIONS=NO
    - cmake --build build
    - sudo cmake --build build --target install
    - cd ..
    - git clone https://github.com/commonmark/cmark.git && cd cmark
    - cmake . -Bbuild -LA -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=install -DCMARK_SHARED=ON -DCMARK_STATIC=ON -DCMARK_TESTS=OFF
    - cmake --build build --target install
    - cd ..
    - cmake . -Bbuild -LA -DUSE_INTREE_LIBQMC=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=install -DOlm_DIR="olm/install/lib/cmake/Olm" -DQt5Keychain_DIR="qtkeychain/install/lib/x86_64-linux-gnu/cmake/Qt5Keychain" -DCMARK_LIBRARY="$PWD/cmark/install/lib/libcmark.a" -DCMARK_INCLUDE_DIR="$PWD/cmark/install/include"
    - cmake --build build --target install
    - linuxdeployqt install/share/applications/org.eu.encom.spectral.desktop -appimage -qmldir=qml -qmldir=imports

build-flatpak:
  image: registry.gitlab.com/b0/flatpak-kde-docker
  stage: build
  script:
    - cd flatpak
    - flatpak-builder --force-clean --ccache --repo=repo build-dir org.eu.encom.spectral.yaml
    - flatpak build-bundle repo spectral.flatpak org.eu.encom.spectral
    - cd ../
    - mv flatpak/spectral.flatpak ./spectral.flatpak
  cache:
    key: "flatpak-$CI_COMMIT_REF_SLUG"
    paths:
    - flatpak/.flatpak-builder
  artifacts:
    paths:
    - spectral.flatpak

build-osx:
  stage: build
  tags:
    - osx
  script:
    - brew install cmark
    - rm -rf olm
    - git clone https://gitlab.matrix.org/matrix-org/olm.git
    - pushd olm
    - cmake . -Bbuild -LA -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=install -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.13.1/ -DBUILD_SHARED_LIBS=NO
    - cmake --build build --target install --parallel 16
    - popd
    - rm -rf qtkeychain
    - git clone https://github.com/frankosterfeld/qtkeychain.git
    - pushd qtkeychain
    - cmake . -Bbuild -LA -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=install -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.13.1/ -DQTKEYCHAIN_STATIC=ON
    - cmake --build build --target install --parallel 16
    - popd
    - cmake . -Bbuild -LA -DUSE_INTREE_LIBQMC=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.13.1/ -DOlm_DIR="olm/install/lib/cmake/Olm" -DQt5Keychain_DIR="qtkeychain/install/lib/cmake/Qt5Keychain"
    - cmake --build build --target all --parallel 16
    - /usr/local/Cellar/qt/5.13.1/bin/macdeployqt build/spectral.app -dmg -qmldir=qml -qmldir=imports
    - mv build/spectral.dmg ./spectral.dmg
  artifacts:
    paths:
    - spectral.dmg

